import { describe, expect, it } from "vitest";
import {
  DUMMY_PASSWORD_DIGEST,
  hashLocalPassword,
  localPasswordIsValid,
  localPasswordNeedsRehash,
  verifyLocalPassword,
} from "./password-hash.js";

describe("local administrator password hashing", () => {
  it("stores a salted scrypt digest and verifies only the original password", async () => {
    const password = "Correct horse battery staple 2026";
    const first = await hashLocalPassword(password, Buffer.alloc(16, 1));
    const second = await hashLocalPassword(password, Buffer.alloc(16, 2));

    expect(first).toMatch(/^scrypt\$131072\$8\$1\$/);
    expect(first).not.toBe(second);
    await expect(verifyLocalPassword(password, first)).resolves.toBe(true);
    await expect(verifyLocalPassword("incorrect password", first)).resolves.toBe(false);
    expect(localPasswordNeedsRehash(first)).toBe(false);
  }, 20_000);

  it("fails closed for malformed digests while retaining the expensive verification path", async () => {
    await expect(verifyLocalPassword("any supplied password", "not-a-digest")).resolves.toBe(false);
    await expect(verifyLocalPassword("any supplied password", DUMMY_PASSWORD_DIGEST)).resolves.toBe(false);
  }, 20_000);

  /*
   * The half of `localPasswordNeedsRehash` that does the work, and had no test.
   *
   * The suite asserted only that a freshly written digest does *not* need
   * rehashing, which every implementation returning a constant `false` also
   * satisfies. What the function exists for is the other answer: recognising a
   * digest written under parameters this build no longer uses. Nothing in
   * production calls it yet -- see the gap recorded on the function itself --
   * so this is the only thing standing between a future cost increase and a
   * predicate that was never right.
   *
   * The digests below are shaped by hand rather than produced by
   * `hashLocalPassword`, because that function can only ever write the current
   * parameters. A stored digest from an older build is exactly what cannot be
   * generated by the current one.
   */
  it("recognises a digest written under parameters this build no longer uses", async () => {
    const current = await hashLocalPassword("Correct horse battery staple 2026", Buffer.alloc(16, 1));
    const [, cost, blockSize, parallelization, salt, hash] = current.split("$");

    expect(localPasswordNeedsRehash(current)).toBe(false);
    expect(localPasswordNeedsRehash(["scrypt", "16384", blockSize, parallelization, salt, hash].join("$"))).toBe(true);
    expect(localPasswordNeedsRehash(["scrypt", cost, "4", parallelization, salt, hash].join("$"))).toBe(true);
    expect(localPasswordNeedsRehash(["scrypt", cost, blockSize, "2", salt, hash].join("$"))).toBe(true);
    // Unparseable counts as stale: there is nothing to verify against, so the
    // only safe answer is that this digest must not be kept.
    expect(localPasswordNeedsRehash("not-a-digest")).toBe(true);
  }, 20_000);

  it("enforces the bounded password policy", () => {
    expect(localPasswordIsValid("too-short")).toBe(false);
    expect(localPasswordIsValid("long-enough-password")).toBe(true);
    expect(localPasswordIsValid("x".repeat(1_025))).toBe(false);
  });
});
