import { z } from "zod";

export const GUARDRAIL_POLICY_STATUSES = ["DRAFT", "ACTIVE", "SUSPENDED"] as const;
export const guardrailPolicyStatusSchema = z.enum(GUARDRAIL_POLICY_STATUSES);
export const guardrailPolicyIdentifierSchema = z.uuid();

const policySlugSchema = z.string().trim().min(2).max(64)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);

/**
 * How a rule's pattern is written, which decides how it is compiled.
 *
 * The first three exist so that most rules never involve a regular expression
 * at all: the operator writes a word and the compiler escapes it, which makes a
 * catastrophic pattern impossible by construction rather than by review. REGEX
 * is the escape hatch, and it is the only type that has to pass
 * `assertPatternIsSafe` before it can be stored.
 */
export const GUARDRAIL_RULE_TYPES = ["WORD", "PHRASE", "PREFIX", "REGEX"] as const;
export const guardrailRuleTypeSchema = z.enum(GUARDRAIL_RULE_TYPES);

/**
 * What happens when a rule matches.
 *
 * FLAG is the one worth explaining: it changes neither the decision nor the
 * text, and exists so a new rule can be measured against live traffic before it
 * is trusted to refuse anything. A rule switched straight to BLOCK on a guess
 * is how a guardrail becomes an outage.
 */
export const GUARDRAIL_RULE_ACTIONS = ["BLOCK", "REDACT", "FLAG"] as const;
export const guardrailRuleActionSchema = z.enum(GUARDRAIL_RULE_ACTIONS);

export const guardrailRuleSchema = z.object({
  /*
   * Stable across edits, and generated by the client rather than the database
   * because a rule is a member of a jsonb array rather than a row. It is what
   * makes an audit event from six months ago still resolvable to the rule that
   * caused it, even after the policy has been versioned several times.
   */
  id: z.uuid(),
  /** What an operator sees in a refusal. The pattern itself is never shown to a user. */
  label: z.string().trim().min(1).max(120),
  type: guardrailRuleTypeSchema,
  pattern: z.string().trim().min(1).max(200),
  action: guardrailRuleActionSchema,
  caseSensitive: z.boolean(),
  enabled: z.boolean(),
}).strict();

/**
 * A policy's rule list.
 *
 * Capped, because every enabled rule is evaluated against every inspected
 * message: an unbounded list is how a policy quietly becomes a latency budget.
 * A hundred is in keeping with the other array bounds in these contracts
 * (`oidcGroupSchema` at 100, `agentSkillReferenceSchema` at 200).
 */
const guardrailRuleListSchema = z.array(guardrailRuleSchema).max(100);

/**
 * The output ceiling an operator may *write*.
 *
 * Deliberately smaller than the bound `guardrailPolicySchema` will *read*, and
 * the asymmetry is the point. `submitRun` clamps with `Math.min(200_000, …)`,
 * so anything above this was never honoured -- but the read schema validates
 * rows on the way out of `GET /api/v1/admin/guardrails`, and tightening it
 * there would turn every deployment holding an older, larger value into a 500
 * on a screen that works today. So the write bound moves and the read bound
 * stays. Do not "tidy" them into agreement.
 */
const writableOutputCharactersSchema = z.number().int().min(1_024).max(200_000);

export const guardrailPolicySchema = z.object({
  id: z.uuid(),
  slug: policySlugSchema,
  displayName: z.string().trim().min(2).max(120),
  description: z.string().trim().min(3).max(500),
  version: z.string().trim().min(1).max(120),
  status: guardrailPolicyStatusSchema,
  maxInputCharacters: z.number().int().min(256).max(32_000),
  // The wide bound, on the read path only. See `writableOutputCharactersSchema`.
  maxOutputCharacters: z.number().int().min(1_024).max(1_000_000),
  blockControlCharacters: z.boolean(),
  blockCredentialPatterns: z.boolean(),
  rules: guardrailRuleListSchema,
  firstActivatedAt: z.iso.datetime().nullable(),
  revision: z.number().int().positive(),
  createdBy: z.uuid().nullable(),
  updatedBy: z.uuid().nullable(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
}).superRefine(({ status, firstActivatedAt }, context) => {
  if (status === "ACTIVE" && !firstActivatedAt) {
    context.addIssue({ code: "custom", path: ["firstActivatedAt"], message: "Active policies require an activation timestamp." });
  }
});

export const guardrailPolicyListSchema = z.object({ items: z.array(guardrailPolicySchema) });

export const createGuardrailPolicySchema = z.object({
  slug: policySlugSchema,
  displayName: z.string().trim().min(2).max(120),
  description: z.string().trim().min(3).max(500),
  version: z.string().trim().min(1).max(120),
  maxInputCharacters: z.number().int().min(256).max(32_000),
  maxOutputCharacters: writableOutputCharactersSchema,
  blockControlCharacters: z.boolean(),
  blockCredentialPatterns: z.boolean(),
  rules: guardrailRuleListSchema.default([]),
}).strict();

export const updateGuardrailPolicySchema = z.object({
  displayName: z.string().trim().min(2).max(120).optional(),
  description: z.string().trim().min(3).max(500).optional(),
  version: z.string().trim().min(1).max(120).optional(),
  maxInputCharacters: z.number().int().min(256).max(32_000).optional(),
  maxOutputCharacters: writableOutputCharactersSchema.optional(),
  blockControlCharacters: z.boolean().optional(),
  blockCredentialPatterns: z.boolean().optional(),
  rules: guardrailRuleListSchema.optional(),
  expectedRevision: z.number().int().positive(),
}).strict();

export const changeGuardrailPolicyStateSchema = z.object({
  expectedRevision: z.number().int().positive(),
  reason: z.string().trim().min(3).max(500),
}).strict();

export type GuardrailRuleType = z.infer<typeof guardrailRuleTypeSchema>;
export type GuardrailRuleAction = z.infer<typeof guardrailRuleActionSchema>;
export type GuardrailRule = z.infer<typeof guardrailRuleSchema>;
export type GuardrailPolicyStatus = z.infer<typeof guardrailPolicyStatusSchema>;
export type GuardrailPolicy = z.infer<typeof guardrailPolicySchema>;
export type GuardrailPolicyList = z.infer<typeof guardrailPolicyListSchema>;
export type CreateGuardrailPolicy = z.infer<typeof createGuardrailPolicySchema>;
export type UpdateGuardrailPolicy = z.infer<typeof updateGuardrailPolicySchema>;
export type ChangeGuardrailPolicyState = z.infer<typeof changeGuardrailPolicyStateSchema>;
